# ─────────────────────────────────────────────
#  Personal Finance Tracker — Configuration
# ─────────────────────────────────────────────

# Application metadata
app.name=Personal Finance Tracker
app.version=1.0.0
app.author=Ange Aurele TUYISENGE

# Database
db.dir=${user.home}/.financetracker
db.filename=finance.db

# UI defaults
ui.default.theme=DARK
ui.default.currency=USD
ui.window.min.width=1024
ui.window.min.height=680

# Export
export.default.months=12
